### ISSUE TITLE
GLogin::Codec::DecodingError in home page

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#159]
```
GLogin::Codec::DecodingError
	/app/vendor/bundle/ruby/2.7.0/gems/glogin-0.10.0/lib/glogin/codec.rb:52:in `decrypt'
	/app/vendor/bundle/ruby/2.7.0/gems/glogin-0.10.0/lib/glogin/cookie.rb:57:in `to_user'
	/app/mailanes.rb:168:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `call'
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `block in compile!'
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1068:in `block in process_route'
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `catch'
	/app/vendor/bundle/ruby/2.7.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `process_route'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`
