### ISSUE TITLE
Error on subscription when user already subscribed

### ISSUE THREAD

**Issue by oridan** [yegor256/mailanes#17]
After submited the subscription the following messager apear: 

```
Internal error at 0.0.0

You have already been subscribed
	/app/mailanes.rb:375:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

```

**Comment by yegor256** [comment]
@oridan this is fixed already, thanks for reporting
