### ISSUE TITLE
nil in auth

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#60]
```
RuntimeError: Code can't be nil
  from glogin/auth.rb:53:in `user'
  from mailanes.rb:168:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
  from sinatra/base.rb:1040:in `block in process_route'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.5`
