### ISSUE TITLE
OpenSSL::Cipher::CipherError: bad decrypt

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#61]
```
OpenSSL::Cipher::CipherError: bad decrypt
  from glogin/codec.rb:54:in `final'
  from glogin/codec.rb:54:in `decrypt'
  from mailanes.rb:161:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.6`
