### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#67]
```
undefined method `[]' for nil:NilClass
	/app/objects/letter.rb:122:in `block in move'
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:151:in `block in transaction'
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:184:in `connect'
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.6.2/lib/pgtk/pool.rb:149:in `transaction'
	/app/objects/letter.rb:112:in `move'
	/app/mailanes.rb:438:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.6`
