### ISSUE TITLE
NoMethodError undefined method `<' for nil:NilClass; /app/objects/letter.rb:287

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#73]
```
NoMethodError undefined method `<' for nil:NilClass; /app/objects/letter.rb:287:in `block in deliver_smtp'; /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'; /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'; /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:33:in `catch'; /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:33:in `catch'; /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:108:in `timeout'; /app/objects/letter.rb:281:in `deliver_smtp'; /app/objects/letter.rb:146:in `deliver'; /app/objects/postman.rb:53:in `deliver'; /app/objects/pipeline.rb:180:in `block in fetch_one'; /app/objects/pipeline.rb:163:in `each'; /app/objects/pipeline.rb:163:in `fetch_one'; /app/objects/pipeline.rb:46:in `block in fetch'; /app/objects/pipeline.rb:45:in `loop'; /app/objects/pipeline.rb:45:in `fetch'; /app/mailanes.rb:127:in `block (3 levels) in <top (required)>'; /app/mailanes.rb:123:in `loop'; /app/mailanes.rb:123:in `block (2 levels) in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.2`
