### ISSUE TITLE
Bug - Add Recipient to List

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/mailanes#87]
I encountered the following error when trying to Add a Recipient to my Mail List using my Firefox browser at https://www.mailanes.com/list?id=63

----

Internal error at 0.0.0

Please help us improve our service and submit the following stacktrace to our issue tracker in GitHub: yegor256/mailanes

Bad Request: chat not found: "👍 New recipient `silas@silasreinagel.com` has been added by silasreinagel to your list ["To Arcadia Subscribers"](https://www.mailanes.com/list?id=63) (1 emails are there). There are 0.1 emails joining daily (last 10 days statistics)."
	/app/objects/tbot.rb:82:in `rescue in post'
	/app/objects/tbot.rb:74:in `post'
	/app/objects/tbot.rb:69:in `notify'
	/app/mailanes.rb:649:in `block in <top (required)>'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1635:in `block in compile!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/logger.rb:15:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/common_logger.rb:33:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:231:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:224:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/handler/webrick.rb:86:in `service'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
	/app/vendor/ruby-2.6.0/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by SilasReinagel** [comment]
@yegor256 I contributed $$$ to this project as a bounty for this bug. Thanks in advance!

**Comment by yegor256** [comment]
@SilasReinagel this is really something weird. What is your YAML config for the list?

**Comment by SilasReinagel** [comment]
This issue happens if you have Telegram notify property, if you haven’t
started a conversation with the MailLanes telegram bot.

If you take out the notify property, or you start a conversation, the it
works fine.
