### ISSUE TITLE
Timeout::Error: execution expired

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#95]
```
Timeout::Error: execution expired
  from net/smtp.rb:539:in `initialize'
  from net/smtp.rb:539:in `open'
  from net/smtp.rb:539:in `tcp_socket'
  from net/smtp.rb:549:in `block in do_start'
  from timeout.rb:93:in `block in timeout'
  from timeout.rb:103:in `timeout'
  from net/smtp.rb:548:in `do_start'
  from net/smtp.rb:518:in `start'
  from mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
  from mail/network/delivery_methods/smtp.rb:100:in `deliver!'
  from mail/message.rb:2159:in `do_delivery'
  from mail/message.rb:262:in `deliver'
  from objects/letter.rb:296:in `block in deliver_smtp'
  from timeout.rb:108:in `timeout'
  from objects/letter.rb:295:in `deliver_smtp'
  from objects/letter.rb:156:in `deliver'
  from mailanes.rb:521:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.4`

**Comment by 0crat** [comment]
Job `gh:yegor256/mailanes#95` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
