### ISSUE TITLE
decoy POP3 is broken

### ISSUE THREAD

**Issue by yegor256** [yegor256/mailanes#99]
```
Net::POPAuthenticationError: -ERR [AUTH] Authentication failed.
  from net/pop.rb:1006:in `check_response_auth'
  from net/pop.rb:905:in `auth'
  from net/pop.rb:567:in `do_start'
  from net/pop.rb:537:in `start'
  from objects/decoy.rb:40:in `fetch'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.5`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8cc96566-3d9b-4cde-a1bc-79fab27ca832, thread: pool-161-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.14](https://github.com/zerocracy/farm): Issue: yegor256/mailanes#99, Action: `created`

**Comment by 0crat** [comment]
Job `gh:yegor256/mailanes#99` is not assigned, can't get performer
